import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <header>
            <h1>this is main layout</h1>
            <p>logo</p>
            <p>user</p>
          </header>
          {children}
          <footer>by tagitsu</footer>
        </main>
      </body>
    </html>
  );
}
